#!/bin/sh
base=$(dirname $0)
bootVersion=`grep "project.version=" $base/nuts/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts/nuts.properties | cut -c17-2000`
runtimeVersion=`grep "project.version=" $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties | cut -c17-2000`
echo "detected nuts      version $bootVersion"
echo "detected nuts-core version $runtimeVersion"

bootPath=$base/nuts-bootstrap/net/vpc/app/nuts/nuts/$bootVersion
bootLatestPath=$base/nuts-bootstrap/net/vpc/app/nuts/nuts/LATEST
mkdir -p $bootPath
mkdir -p $bootLatestPath
cp $base/nuts/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts/nuts.properties $bootPath/nuts-$bootVersion.properties

cp $base/nuts/target/nuts-$bootVersion.jar $base/nuts-bootstrap/nuts.jar

echo $bootVersion > $base/nuts-bootstrap/version.txt
h=`pwd`
cd $base/nuts-bootstrap/
tar -cf nuts-bundle.tar.gz nuts nuts.jar version.txt
cd $h


cp $bootPath/nuts-$bootVersion.properties $bootLatestPath/nuts-LATEST.properties
echo "runtimeId=net.vpc.app.nuts:nuts-core#$runtimeVersion" >> $bootPath/nuts-$bootVersion.properties
echo "repositories=http://repo.maven.apache.org/maven2/;https://raw.githubusercontent.com/thevpc/vpc-public-maven/master" >> $bootPath/nuts-$bootVersion.properties

mkdir -p $bootLatestPath
cp $bootPath/nuts-$bootVersion.properties $bootLatestPath/nuts-LATEST.properties

mkdir -p $base/nuts-bootstrap/net/vpc/app/nuts/nuts-core/LATEST
cp $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties $base/nuts-bootstrap/net/vpc/app/nuts/nuts-core/LATEST/nuts-core-LATEST.properties

mkdir -p $base/nuts-bootstrap/net/vpc/app/nuts/nuts-core/$runtimeVersion
cp $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties $base/nuts-bootstrap/net/vpc/app/nuts/nuts-core/$runtimeVersion/nuts-core-$runtimeVersion.properties


cp $base/nuts-bootstrap/nuts.jar $HOME/bin/nuts.jar
cp $base/nuts-bootstrap/nuts $HOME/bin/nuts
cp $base/nuts-bootstrap/nuts-debug $HOME/bin/nuts-debug
