#!/bin/sh
base=$(dirname $0)
bootVersion=`grep "project.version=" $base/nuts/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts/nuts.properties | cut -c17-2000`
runtimeVersion=`grep "project.version=" $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties | cut -c17-2000`
echo "detected nuts      version $bootVersion"
echo "detected nuts-core version $runtimeVersion"

cp $base/nuts/target/nuts-$bootVersion.jar ~/bin/nuts.jar

#vpc_public_nuts=$HOME/vpc-public-nuts

#bootPath=$vpc_public_nuts/net/vpc/app/nuts/nuts/${bootVersion}
#bootLatestPath=$vpc_public_nuts/net/vpc/app/nuts/nuts/LATEST
#mkdir -p $bootPath
#mkdir -p $bootLatestPath
#cp $base/nuts/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts/nuts.properties $bootPath/nuts.properties


#echo $bootVersion > $vpc_public_nuts/version.txt


#echo "bootRuntimeId=net.vpc.app.nuts:nuts-core#$runtimeVersion" >> $bootPath/nuts.properties
#echo "repositories=http://repo.maven.apache.org/maven2/;https://raw.githubusercontent.com/thevpc/vpc-public-maven/master" >> $bootPath/nuts.properties

#mkdir -p $bootLatestPath
#cp $bootPath/nuts.properties $bootLatestPath/nuts.properties

#mkdir -p $vpc_public_nuts/net/vpc/app/nuts/nuts-core/LATEST
#cp $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties $vpc_public_nuts/net/vpc/app/nuts/nuts-core/LATEST/nuts.properties

#mkdir -p $vpc_public_nuts/net/vpc/app/nuts/nuts-core/$runtimeVersion
#cp $base/nuts-core/target/classes/META-INF/nuts/net.vpc.app.nuts/nuts-core/nuts.properties $vpc_public_nuts/net/vpc/app/nuts/nuts-core/$runtimeVersion/nuts.properties

##################################################################"
