#!/bin/bash
NUTS_VERSION=0.8.8

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

NUTS_JAVA_HOME=/home/vpc/.jdks/corretto-1.8.0_452/
NUTS_APP_JAR=~/.m2/repository/net/thevpc/nuts/nuts-app/$NUTS_VERSION/nuts-app-$NUTS_VERSION.jar

# compare_versions_all


if [ x"$NUTS_JAVA_HOME" != "x" ] ; then
    JAVA_CMD="$NUTS_JAVA_HOME/bin/java";
elif [ x"${JAVA_HOME}" != "x" ] ; then
    JAVA_CMD="${JAVA_HOME}/bin/java";
fi

$JAVA_CMD $NUTS_DEBUG_ARG -jar "$NUTS_APP_JAR" -ZyS --stacktrace --sandbox net.thevpc.nuts.installers:nuts-release-tool


