//package net.thevpc.nuts.elem;
//
//public enum NStringLayout {
//    DOUBLE_QUOTED_STRING,
//    SINGLE_QUOTED_STRING,
//    ANTI_QUOTED_STRING,
//    TRIPLE_DOUBLE_QUOTED_STRING,
//    TRIPLE_SINGLE_QUOTED_STRING,
//    TRIPLE_ANTI_QUOTED_STRING,
//    SINGLE_LINE_STRING,
//}
