module.exports = {
   'someSidebar': {
      'apps': [
         'apps/Apps',
         'apps/app-xbinjr',
         'apps/app-xjmeld',
         'apps/app-kifkif',
         'apps/app-ntemplate',
         'apps/app-nuts',
         'apps/app-xomegat',
         'apps/app-pnote',
         'apps/app-dbclient',
         'apps/app-xflappy-bird',
         'apps/app-xtsunami',
         'apps/app-xjd-gui',
         'apps/app-xjdiskreport',
         'apps/app-xjedit',
         'apps/app-jpass',
         'apps/app-xmindustry-desktop',
         'apps/app-xmindustry-server',
         'apps/app-xmucommander',
         'apps/app-ndb',
         'apps/app-ndocusaurus',
         'apps/app-xnetbeans',
         'apps/app-netbeans-launcher',
         'apps/app-njob',
         'apps/app-noapi',
         'apps/app-nserver',
         'apps/app-nsh',
         'apps/app-ntomcat',
         'apps/app-xomnigraph',
         'apps/app-xspring-cli',
         'apps/app-misc',
      ],
      'cmd': [
         'cmd/exec-cmd',
         'cmd/fetch-cmd',
         'cmd/info-cmd',
         'cmd/install-cmd',
         'cmd/license-cmd',
         'cmd/cmds',
         'cmd/search-cmds',
         'cmd/version-cmd',
         'cmd/welcome-cmd',
         'cmd/Commands',
      ],
      'concepts': [
         'concepts/aliases',
         'concepts/automation',
         'concepts/commandline',
         'concepts/filesystem',
         'concepts/doc1',
         'concepts/NutsConcepts',
      ],
      'contributing': [
         'contributing/building',
         'contributing/contributing',
         'contributing/projects',
         'contributing/NutsContributing',
      ],
      'dev': [
         'dev/nutsDescriptorIntegration',
         'dev/nutsPath',
         'dev/nutsStream',
         'dev/nutsApp',
         'dev/ApplicationFramework',
      ],
      'info': [
         'info/running',
         'info/GettingStarted',
         'info/faq',
         'info/troubleshooting',
         'info/changelog',
      ],
      'installation': [
         'installation/Installation',
         'installation/tutorial',
         'installation/installation-prod',
         'installation/installation-preview',
      ],
      'intro': [
         'intro/Introduction',
         'intro/introduction',
         'intro/nutsAndMaven',
         'intro/license',
         'intro/other-resources',
      ],
      'javadocs': [
         'javadocs/API-Documentation',
      ],
'Document': [      'root'],
   }
};