module.exports = {
   'someSidebar': {
      'apps': {
         'cmdline': [
            'apps/cmdline/CommandlineApps',
            'apps/cmdline/app-ntemplate',
            'apps/cmdline/app-nuts',
            'apps/cmdline/app-nversion',
            'apps/cmdline/app-xtsunami',
            'apps/cmdline/app-ncode',
            'apps/cmdline/app-ndb',
            'apps/cmdline/app-ndiff',
            'apps/cmdline/app-ndocusaurus',
            'apps/cmdline/app-njob',
            'apps/cmdline/app-nmvn',
            'apps/cmdline/app-noapi',
            'apps/cmdline/app-nsh',
            'apps/cmdline/app-xspring-cli',
         ],
         'desktop': [
            'apps/desktop/app-xbinjr',
            'apps/desktop/DesktopApps',
            'apps/desktop/app-xjmeld',
            'apps/desktop/app-kifkif',
            'apps/desktop/app-xomegat',
            'apps/desktop/app-pnote',
            'apps/desktop/app-dbclient',
            'apps/desktop/app-xjd-gui',
            'apps/desktop/app-xjdiskreport',
            'apps/desktop/app-xjedit',
            'apps/desktop/app-jpass',
            'apps/desktop/app-xmucommander',
            'apps/desktop/app-netbeans-launcher',
            'apps/desktop/app-xomnigraph',
         ],
         'games': [
            'apps/games/GameApps',
            'apps/games/app-xflappy-bird',
            'apps/games/app-xmindustry',
         ],
         'servers': [
            'apps/servers/ServerApps',
            'apps/servers/app-nserver',
            'apps/servers/app-ntomcat',
         ],
'Apps': [         'apps/Apps'],
'misc': [         'apps/app-misc'],
      },
      'cmd': [
         'cmd/exec-cmd',
         'cmd/fetch-cmd',
         'cmd/info-cmd',
         'cmd/install-cmd',
         'cmd/license-cmd',
         'cmd/cmds',
         'cmd/search-cmds',
         'cmd/version-cmd',
         'cmd/welcome-cmd',
         'cmd/Commands',
      ],
      'concepts': [
         'concepts/aliases',
         'concepts/automation',
         'concepts/commandline',
         'concepts/filesystem',
         'concepts/doc1',
         'concepts/NutsConcepts',
      ],
      'contributing': [
         'contributing/building',
         'contributing/contributing',
         'contributing/projects',
         'contributing/NutsContributing',
      ],
      'dev': [
         'dev/nutsAppNAF',
         'dev/nutsDescriptorIntegration',
         'dev/nutsPath',
         'dev/nutsStream',
         'dev/nutsApp',
         'dev/ApplicationFramework',
      ],
      'info': [
         'info/running',
         'info/GettingStarted',
         'info/faq',
         'info/troubleshooting',
         'info/changelog',
      ],
      'installation': [
         'installation/Installation',
         'installation/tutorial',
         'installation/installation-prod',
         'installation/installation-preview',
      ],
      'intro': [
         'intro/Introduction',
         'intro/introduction',
         'intro/nutsAndMaven',
         'intro/license',
         'intro/other-resources',
      ],
      'javadocs': [
         'javadocs/API-Documentation',
      ],
'Document': [      'root'],
   }
};