# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

# Load user profile if it exists (equivalent to sourcing ~/.bashrc)
if (Test-Path $PROFILE) {
    . $PROFILE
}

# Dot-source the main Nuts environment setup script so environment variables persist
. "$$SCRIPT_NUTS_INIT$$"

# Execute nuts welcome once inside the initialized shell
& "$$SCRIPT_NUTS$$" welcome

# END-COMMAND