#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

if [ -f "~/.bashrc" ]; then
    . "~/.bashrc"
fi

. $$SCRIPT_NUTS_INIT$$
. $$SCRIPT_NUTS$$ welcome

# END-COMMAND