#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

if [ -f "~/.bashrc" ]; then
    . "~/.bashrc"
fi

/bin/bash --init-file $$SCRIPT_NUTS_TERM_INIT$$

# END-COMMAND