#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

. $$SCRIPT_NUTS_ENV$$

if [ -n "$NUTS_JAVA_HOME" ] && [ -x "$NUTS_JAVA_HOME/bin/java" ];  then
    _java="$NUTS_JAVA_HOME/bin/java"
elif (type -p java > /dev/null) ; then
    _java=java
elif [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ];  then
#    echo found java executable in JAVA_HOME
    _java="$JAVA_HOME/bin/java"
else
    _java="java"
fi

if [ "$_java" ]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    major=`echo $version | cut -d. -f1`
    minor=`echo $version | cut -d. -f2`
    if [ "$major" -eq "1" ]; then
        major=$minor
    fi
    if [ "$major" -lt "8" ]; then
        echo expected 1.8+ java version, found $version;
        exit 204;
    fi
fi

if [ x"$1" = x"--debug" ] ; then
  NUTS_DEBUG_ARG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
elif [[ x"$1" = x"--debug="* ]] ; then
  sub=${1:8}
  sub="${sub},"
  d_port=5005
  d_enable="true"
  d_suspend="y"
  subArray=$(echo $sub | tr "," "\n")

  for curr in $subArray
  do
    if [ ! -z "${curr##*[!0-9]*}" ] ; then
         d_port=$curr
      elif [ x"$curr" = 'xno' ] ; then
         d_enable="false"
      elif [ x"$curr" = 'xsuspend' ] ; then
         d_suspend="y"
      elif [ x"$curr" = 'x!suspend' ] ; then
         d_suspend="n"
      elif [ x"$curr" = 'xs' ] ; then
         d_suspend="y"
      elif [ x"$curr" = 'x!s' ] ; then
         d_suspend="n"
      else
        echo $curr is unsupported
      fi
  done

  if [ x$d_enable = x'true' ] ; then
    NUTS_DEBUG_ARG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=$d_suspend,address=$d_port"
  fi
  #echo $sub
fi


_NUTS_JAVA_OPTIONS=`echo "$NUTS_JAVA_OPTIONS -jar" | xargs`


$_java $NUTS_DEBUG_ARG $_NUTS_JAVA_OPTIONS "$$NUTS_JAR$$" -w "$NUTS_WORKSPACE" "$@"
# END-COMMAND
