#!/bin/fish
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

if test -f "~/.config/fish/config.fish"
    . "~/.config/fish/config.fish"
end

/bin/fish --init-file $$SCRIPT_NUTS_TERM_INIT$$

# END-COMMAND