#!/bin/fish
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

if test -f "~/.config/fish/config.fish"
    . "~/.config/fish/config.fish"
end

. $$SCRIPT_NUTS_INIT$$
$$SCRIPT_NUTS$$ welcome

# END-COMMAND