/* Generated By:JavaCC: Do not edit this line. TsonStreamParserImplConstants.java */
package net.thevpc.nuts.runtime.standalone.tson.impl.parser.javacc;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TsonStreamParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATETIME = 1;
  /** RegularExpression Id. */
  int DATE = 2;
  /** RegularExpression Id. */
  int TIME = 3;
  /** RegularExpression Id. */
  int REGEX = 4;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int NUMBER = 7;
  /** RegularExpression Id. */
  int EXPONENT = 8;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_STR = 9;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_STR = 10;
  /** RegularExpression Id. */
  int LINE_STR = 11;
  /** RegularExpression Id. */
  int ANTI_QUOTE_STR = 12;
  /** RegularExpression Id. */
  int TRIPLE_DOUBLE_QUOTE_STR = 13;
  /** RegularExpression Id. */
  int TRIPLE_SINGLE_QUOTE_STR = 14;
  /** RegularExpression Id. */
  int TRIPLE_ANTI_QUOTE_STR = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int LPAREN = 19;
  /** RegularExpression Id. */
  int RPAREN = 20;
  /** RegularExpression Id. */
  int LBRACK = 21;
  /** RegularExpression Id. */
  int RBRACK = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int OP_PLUS = 24;
  /** RegularExpression Id. */
  int OP_PLUS2 = 25;
  /** RegularExpression Id. */
  int OP_PLUS3 = 26;
  /** RegularExpression Id. */
  int OP_MINUS = 27;
  /** RegularExpression Id. */
  int OP_MINUS2 = 28;
  /** RegularExpression Id. */
  int OP_MINUS3 = 29;
  /** RegularExpression Id. */
  int OP_MUL = 30;
  /** RegularExpression Id. */
  int OP_MUL2 = 31;
  /** RegularExpression Id. */
  int OP_MUL3 = 32;
  /** RegularExpression Id. */
  int OP_DIV = 33;
  /** RegularExpression Id. */
  int OP_DIV3 = 34;
  /** RegularExpression Id. */
  int OP_HAT = 35;
  /** RegularExpression Id. */
  int OP_HAT2 = 36;
  /** RegularExpression Id. */
  int OP_HAT3 = 37;
  /** RegularExpression Id. */
  int OP_REM = 38;
  /** RegularExpression Id. */
  int OP_REM2 = 39;
  /** RegularExpression Id. */
  int OP_REM3 = 40;
  /** RegularExpression Id. */
  int OP_EQ = 41;
  /** RegularExpression Id. */
  int OP_EQ2 = 42;
  /** RegularExpression Id. */
  int OP_EQ3 = 43;
  /** RegularExpression Id. */
  int OP_TILDE = 44;
  /** RegularExpression Id. */
  int OP_TILDE2 = 45;
  /** RegularExpression Id. */
  int OP_TILDE3 = 46;
  /** RegularExpression Id. */
  int OP_LT = 47;
  /** RegularExpression Id. */
  int OP_LT2 = 48;
  /** RegularExpression Id. */
  int OP_LT3 = 49;
  /** RegularExpression Id. */
  int OP_GT = 50;
  /** RegularExpression Id. */
  int OP_GT2 = 51;
  /** RegularExpression Id. */
  int OP_GT3 = 52;
  /** RegularExpression Id. */
  int OP_LTE = 53;
  /** RegularExpression Id. */
  int OP_GTE = 54;
  /** RegularExpression Id. */
  int OP_ASSIGN = 55;
  /** RegularExpression Id. */
  int OP_ASSIGN_EQ = 56;
  /** RegularExpression Id. */
  int OP_MINUS_GT = 57;
  /** RegularExpression Id. */
  int OP_MINUS2_GT = 58;
  /** RegularExpression Id. */
  int OP_EQ_GT = 59;
  /** RegularExpression Id. */
  int OP_EQ2_GT = 60;
  /** RegularExpression Id. */
  int OP_LT_MINUS2 = 61;
  /** RegularExpression Id. */
  int OP_LT_EQ2 = 62;
  /** RegularExpression Id. */
  int OP_PIPE = 63;
  /** RegularExpression Id. */
  int OP_PIPE2 = 64;
  /** RegularExpression Id. */
  int OP_PIPE3 = 65;
  /** RegularExpression Id. */
  int OP_AND = 66;
  /** RegularExpression Id. */
  int OP_AND2 = 67;
  /** RegularExpression Id. */
  int OP_AND3 = 68;
  /** RegularExpression Id. */
  int OP_HASH = 69;
  /** RegularExpression Id. */
  int OP_HASH2 = 70;
  /** RegularExpression Id. */
  int OP_HASH3 = 71;
  /** RegularExpression Id. */
  int OP_HASH4 = 72;
  /** RegularExpression Id. */
  int OP_HASH5 = 73;
  /** RegularExpression Id. */
  int OP_HASH6 = 74;
  /** RegularExpression Id. */
  int OP_HASH7 = 75;
  /** RegularExpression Id. */
  int OP_HASH8 = 76;
  /** RegularExpression Id. */
  int OP_HASH9 = 77;
  /** RegularExpression Id. */
  int OP_HASH10 = 78;
  /** RegularExpression Id. */
  int SEMICOLON = 79;
  /** RegularExpression Id. */
  int SEMICOLON2 = 80;
  /** RegularExpression Id. */
  int COMMA = 81;
  /** RegularExpression Id. */
  int AT = 82;
  /** RegularExpression Id. */
  int AT2 = 83;
  /** RegularExpression Id. */
  int CHARSTREAM_START = 84;
  /** RegularExpression Id. */
  int ALIAS = 85;
  /** RegularExpression Id. */
  int NAME = 86;
  /** RegularExpression Id. */
  int LETTER = 87;
  /** RegularExpression Id. */
  int DIGIT = 88;
  /** RegularExpression Id. */
  int CHARSTREAM_END = 89;
  /** RegularExpression Id. */
  int CHARSTREAM_PART = 90;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_CHARSTREAM = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DATETIME>",
    "<DATE>",
    "<TIME>",
    "<REGEX>",
    "\"{\"",
    "\"}\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<DOUBLE_QUOTE_STR>",
    "<SINGLE_QUOTE_STR>",
    "<LINE_STR>",
    "<ANTI_QUOTE_STR>",
    "<TRIPLE_DOUBLE_QUOTE_STR>",
    "<TRIPLE_SINGLE_QUOTE_STR>",
    "<TRIPLE_ANTI_QUOTE_STR>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\"+\"",
    "\"++\"",
    "\"+++\"",
    "\"-\"",
    "\"--\"",
    "\"---\"",
    "\"*\"",
    "\"**\"",
    "\"***\"",
    "\"/\"",
    "\"///\"",
    "\"^\"",
    "\"^^\"",
    "\"^^^\"",
    "\"%\"",
    "\"%%\"",
    "\"%%%\"",
    "\"=\"",
    "\"==\"",
    "\"===\"",
    "\"~\"",
    "\"~~\"",
    "\"~~~\"",
    "\"<\"",
    "\"<<\"",
    "\"<<<\"",
    "\">\"",
    "\">>\"",
    "\">>>\"",
    "\"<=\"",
    "\">=\"",
    "\":=\"",
    "\":==\"",
    "\"->\"",
    "\"-->\"",
    "\"=>\"",
    "\"==>\"",
    "\"<--\"",
    "\"<==\"",
    "\"|\"",
    "\"||\"",
    "\"|||\"",
    "\"&\"",
    "\"&&\"",
    "\"&&&\"",
    "\"#\"",
    "\"##\"",
    "\"###\"",
    "\"####\"",
    "\"#####\"",
    "\"######\"",
    "\"#######\"",
    "\"########\"",
    "\"#########\"",
    "\"##########\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"@\"",
    "\"@@\"",
    "<CHARSTREAM_START>",
    "<ALIAS>",
    "<NAME>",
    "<LETTER>",
    "<DIGIT>",
    "\"]\"",
    "<CHARSTREAM_PART>",
    "<token of kind 91>",
    "<token of kind 92>",
    "<token of kind 93>",
  };

}
