#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

#!/bin/bash
# THIS FILE IS GENERATED BY net.thevpc.nuts:nuts-runtime
# DO NOT EDIT IT MANUALLY

# Bash's default COMP_WORDBREAKS treats '=' and ':' as word separators,
# which splits "-w=value" into two tokens ("-w" and "=value") before
# completion even runs. Remove them so attached-value flags stay one word.
COMP_WORDBREAKS=${COMP_WORDBREAKS//=}
COMP_WORDBREAKS=${COMP_WORDBREAKS//:}

_nuts_completions() {
    local cur cword offset word_start i raw line value directive
    cword=$COMP_CWORD
    cur=${COMP_WORDS[cword]}

    word_start=0
    for ((i=1; i<cword; i++)); do
        word_start=$(( word_start + ${#COMP_WORDS[i]} + 1 ))
    done
    offset=$(( COMP_POINT - word_start ))
    (( offset < 0 )) && offset=0
    (( offset > ${#cur} )) && offset=${#cur}

    raw=$(nuts "--nuts-exec-mode=complete,$((cword - 1)),$offset" "${COMP_WORDS[@]:1}" 2>/dev/null)

    COMPREPLY=()
    directive=""
    local -a matches=()
    while IFS= read -r line; do
        if [[ "$line" == ::* ]]; then
            directive="${line:2}"
            continue
        fi
        value="${line%%$'\t'*}"
        [[ "$value" == "$cur"* ]] && matches+=( "$value" )
    done <<< "$raw"

    COMPREPLY=( "${matches[@]}" )

    case ",$directive," in
        *,nospace,*) compopt -o nospace 2>/dev/null ;;
    esac
    case ",$directive," in
        *,filenames,*) compopt -o filenames 2>/dev/null ;;
    esac
    case ",$directive," in
        *,nosort,*) compopt -o nosort 2>/dev/null ;;
    esac
}
complete -F _nuts_completions nuts

# END-COMMAND
