#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

#!/bin/zsh
# THIS FILE IS GENERATED BY net.thevpc.nuts:nuts-runtime
# DO NOT EDIT IT MANUALLY

_nuts_completions() {
    local raw line value directive
    local cword=$(( CURRENT - 2 ))
    local offset=${#PREFIX}

    raw=$(nuts "--nuts-exec-mode=complete,${cword},${offset}" "${words[@]:1}" 2>/dev/null)

    local -a matches
    matches=()
    directive=""
    while IFS= read -r line; do
        if [[ "$line" == ::* ]]; then
            directive="${line:2}"
            continue
        fi
        value="${line%%$'\t'*}"
        matches+=( "$value" )
    done <<< "$raw"

    case ",$directive," in
        *,filenames,*) _files ;;
    esac

    if (( ${#matches[@]} )); then
        case ",$directive," in
            *,nospace,*)
                case ",$directive," in
                    *,nosort,*) compadd -S '' -V unsorted -a matches ;;
                    *)          compadd -S '' -a matches ;;
                esac
                ;;
            *)
                case ",$directive," in
                    *,nosort,*) compadd -V unsorted -a matches ;;
                    *)          compadd -a matches ;;
                esac
                ;;
        esac
    fi
}

if (( $+functions[compdef] )); then
    compdef _nuts_completions nuts
fi

# END-COMMAND