#!/bin/fish
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

# THIS FILE IS GENERATED BY net.thevpc.nuts:nuts-runtime
# DO NOT EDIT IT MANUALLY

function __nuts_complete
    set -l tokens (commandline -opc)
    set -l cur (commandline -ct)
    set -l cword (math (count $tokens) - 1)
    set -l offset (string length -- $cur)

    set -l raw (nuts "--nuts-exec-mode=complete,$cword,$offset" $tokens[2..-1] $cur 2>/dev/null)
    for line in $raw
        if string match -q '::*' -- $line
            continue
        end
        set -l parts (string split \t -- $line)
        echo $parts[1]
    end
end
complete -c nuts -f -a '(__nuts_complete)'

# END-COMMAND
