# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

# THIS FILE IS GENERATED BY net.thevpc.nuts:nuts-runtime
# DO NOT EDIT IT MANUALLY


# THIS FILE IS GENERATED BY net.thevpc.nuts:nuts-runtime
# DO NOT EDIT IT MANUALLY

Register-ArgumentCompleter -Native -CommandName nuts -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    # Build the word array exactly as bash's COMP_WORDS/zsh's $words would:
    # tokens after the command name, in order, including the (possibly partial)
    # current word.
    $allTokens = $commandAst.CommandElements | Select-Object -Skip 1
    $words = @()
    $cword = -1
    $offset = 0

    for ($i = 0; $i -lt $allTokens.Count; $i++) {
        $tokenText = $allTokens[$i].Extent.Text
        $tokenStart = $allTokens[$i].Extent.StartOffset
        $tokenEnd = $allTokens[$i].Extent.EndOffset
        $words += $tokenText
        if ($cursorPosition -ge $tokenStart -and $cursorPosition -le $tokenEnd) {
            $cword = $i
            $offset = $cursorPosition - $tokenStart
        }
    }
    # cursor sits past the last recognized token (typing a brand-new word)
    if ($cword -eq -1) {
        $cword = $words.Count
        $words += $wordToComplete
        $offset = $wordToComplete.Length
    }

    $modeArg = "--nuts-exec-mode=complete,$cword,$offset"
    $raw = & nuts $modeArg @words 2>$null

    $directive = ""
    $matches = @()
    foreach ($line in $raw -split "`n") {
        if ($line -like '::*') {
            $directive = $line.Substring(2)
            continue
        }
        $parts = $line -split "`t", 2
        $value = $parts[0]
        $label = if ($parts.Count -gt 1) { $parts[1] } else { $value }
        if ($value.StartsWith($wordToComplete)) {
            $matches += [System.Management.Automation.CompletionResult]::new(
                $value, $label, 'ParameterValue', $label
            )
        }
    }
    $matches
}

# END-COMMAND