#!/bin/sh 
asciidoctor_baseDir=$(dirname $0)
shared_baseDir=${asciidoctor_baseDir}/../shared/asciidoctor
# sudo gem install asciidoctor-mathematical
# docker run -d --name plantuml -p 8081:8080 plantuml/plantuml-server:jetty
# -r asciidoctor-latexmath

for f in $asciidoctor_baseDir/*.adoc
do
PLANTUML_URL="http://localhost:8081/" asciidoctor-pdf -r asciidoctor-diagram -a "pdf-themesdir=${shared_baseDir}/resources/themes" -a "pdf-theme=default" -a "pdf-fontsdir=${shared_baseDir}/resources/fonts/;GEM_FONTS_DIR" "$f"
done
