# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

# If you are using Windows Terminal (wt.exe) uncomment this line
# if (-not $env:NUTS_SYS_TERM_START) { $env:NUTS_SYS_TERM_START = "wt.exe powershell.exe -NoExit -ExecutionPolicy Bypass -File" }

# If you are using PowerShell Core / PS 7+ (pwsh.exe) uncomment this line
# if (-not $env:NUTS_SYS_TERM_START) { $env:NUTS_SYS_TERM_START = "pwsh.exe -NoExit -ExecutionPolicy Bypass -File" }

# Default to standard Windows PowerShell (powershell.exe)
if (-not $env:NUTS_SYS_TERM_START) {
    $env:NUTS_SYS_TERM_START = "powershell.exe -NoExit -ExecutionPolicy Bypass -File"
}

Invoke-Expression "$env:NUTS_SYS_TERM_START `"$$SCRIPT_NUTS_TERM_INIT$$`""

# END-COMMAND