package net.vpc.app.nuts.toolbox.ndi;

import net.vpc.app.nuts.*;
import net.vpc.app.nuts.app.NutsApplicationContext;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class LinuxNdi {
    private NutsApplicationContext appContext;

    public LinuxNdi(NutsApplicationContext appContext) {
        this.appContext = appContext;
    }

    public void createNutsScript(String id, boolean force, boolean forceBoot, boolean silent, boolean fetch) throws IOException {
        if ("nuts".equals(id)) {
            createBootScript(forceBoot||force,false);
        } else {
            createBootScript(false,true);
            NutsId nutsId = appContext.getWorkspace().getParseManager().parseId(id);
            NutsDefinition fetched=null;
            if(nutsId.getVersion().isEmpty()){
                fetched = appContext.getWorkspace().fetch(id, null);
                nutsId=fetched.getId().getSimpleNameId();
                //nutsId=fetched.getId().getLongNameId();
            }
            if(fetch){
                if(fetched==null){
                    fetched = appContext.getWorkspace().fetch(id, null);
                }
                //appContext.out().printf("==%s== resolved as ==%s==\n", id,fetched.getId());
            }
            String n = nutsId.getName();
            File ff = getScriptFile(n);
            boolean exists = ff.exists();
            if (!force && exists) {
                if(!silent) {
                    appContext.out().printf("Script already exists ==%s==\n", ff.getPath());
                }
            } else {
                String idContent = "RUN : " + nutsId;
                createScript(n, silent, nutsId.toString(), idContent, "nuts \"" + nutsId+"\" \"$@\"");
            }
        }
    }

    public void createBootScript(boolean force,boolean silent) throws IOException {
        NutsId b = appContext.getWorkspace().getConfigManager().getRunningContext().getApiId();
        NutsDefinition f = appContext.getWorkspace().fetch(b.toString(), null);
        File ff = getScriptFile("nuts");
        if (!force && ff.exists()) {
            if (!silent) {
                appContext.out().printf("Script already exists ==%s==\n", ff.getPath());
            }
        } else {
            String idContent = "BOOT : " + f.getId().toString();
            createScript("nuts", silent, f.getId().getLongName(), idContent, "java -jar \"" + f.getFile()+"\" \"$@\"");
        }
    }

    public File getScriptFile(String name) {
        File bin = new File(System.getProperty("user.home"), "bin");
        return new File(bin, name);
    }

    public File createScript(String name, boolean silent, String desc, String idContent, String content) throws IOException {
        File script = getScriptFile(name);
        if (script.getParentFile() != null) {
            if (!script.getParentFile().exists()) {
                if(!silent) {
                    appContext.out().printf("Creating folder ==%s==\n", script.getParentFile().getPath());
                }
                script.getParentFile().mkdirs();
            }
        }
        if(!silent) {
            if (script.exists()) {
                appContext.out().printf("Install script (with override) ==%s== for ==%s==\n", script.getPath(), desc);
            } else {
                appContext.out().printf("Install script ==%s== for ==%s==\n", script.getPath(), desc);
            }
        }

        try (FileWriter w = new FileWriter(script)) {
            w.write("#!/bin/sh\n");
            w.write("# THIS FILE IS GENERATED BY\n");
            w.write("#      net.vpc.app.nuts.toolbox.ndi\n");
            w.write("# DO NOT EDIT IT MANUALLY\n");
            w.write("#\n");
            w.write("# START-ID\n");
            for (String s : idContent.split("\n")) {
                w.write("# "+s+"\n");
            }
            w.write("# END-ID\n");
            w.write("#\n");
            w.write("# START-COMMAND\n");
            w.write("\n");
            w.write(content);
            if(!content.endsWith("\n") && !content.endsWith("\r")){
                w.write("\n");
            }
            w.write("\n");
            w.write("# END-COMMAND\n");
            w.write("\n");
        }
        script.setExecutable(true);
        return script;
    }
}
