#!/bin/bash
rm -Rf /home/vpc/.config/nuts/
rm -Rf /home/vpc/.local/share/nuts/
rm -Rf /home/vpc/.local/bin/nuts/
rm -Rf /home/vpc/.local/lib/nuts/
rm -Rf /home/vpc/.local/log/nuts/
rm -Rf /home/vpc/.local/state/nuts/
rm -Rf /home/vpc/xprojects/nuts/nuts-community/test/nuts-runtime-test/runtime/test