#!/usr/bin/env pwsh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

. "$$SCRIPT_NUTS_ENV$$"

# --- resolve the java executable used to run the nuts launcher itself ---
# Order: NUTS_JAVA_HOME -> JAVA_HOME -> java on PATH.
# No download/auto-provisioning here on purpose: a bootstrap JVM is required
# to even run nuts-app.jar, so there is no Java code yet to delegate to.
# Version/JDK selection for the app that nuts *launches* is nuts' own job,
# once it is running.
$_java = $null
if ($env:NUTS_JAVA_HOME -and (Test-Path (Join-Path $env:NUTS_JAVA_HOME 'bin\java.exe'))) {
    $_java = Join-Path $env:NUTS_JAVA_HOME 'bin\java.exe'
} elseif ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME 'bin\java.exe'))) {
    $_java = Join-Path $env:JAVA_HOME 'bin\java.exe'
} else {
    $cmd = Get-Command java -ErrorAction SilentlyContinue
    if ($cmd) { $_java = $cmd.Source }
}
if (-not $_java) {
    [Console]::Error.WriteLine('no java found (checked NUTS_JAVA_HOME, JAVA_HOME, PATH); please install a JDK 8+ or set NUTS_JAVA_HOME/JAVA_HOME')
    exit 203
}

# "openjdk version "21.0.10" ..." / "java version "1.8.0_202"" -> capture group
$verOutput = (& $_java '-version' 2>&1 | Out-String)
$jver = $null
$m = [regex]::Match($verOutput, 'version\s+"([^"]+)"')
if ($m.Success) { $jver = $m.Groups[1].Value }

# "1.8.0_202" -> 8 ; "17.0.2" -> 17 ; "11-ea" -> 11 ; "21" -> 21
$major = $null
if ($jver) {
    if ($jver -match '^1\.(\d+)') {
        $major = $Matches[1]
    } elseif ($jver -match '^(\d+)') {
        $major = $Matches[1]
    }
}

if (-not $major -or -not ($major -match '^\d+$')) {
    [Console]::Error.WriteLine("warning: unable to determine java version from '$jver', skipping version check")
    $major = $null
} elseif ([int]$major -lt 8) {
    [Console]::Error.WriteLine("expected 1.8+ java version, found $jver")
    exit 204
}

# --- parse launcher-only options from the leading arguments ---
# These configure how THIS launcher (nuts) itself is started (the bootstrap
# JVM). They are consumed here and NOT forwarded to nuts.
#
# All of them live under "--" (double-dash), since single-dash is nuts' own
# combinable short-option space and must not be shadowed here.
#
#   --J=<jvmopt>       forward <jvmopt> verbatim as an extra JVM option to
#                         the launcher (repeatable), e.g. --J=-Xmx512m
#   --jdb               attach a debugger to the launcher's own JVM on port
#                         5005, suspended
#   --jdb=[port][,opt[,opt...]]  configure the launcher debug agent:
#                         no             disable debug
#                         suspend | s     suspend=y
#                         ~suspend | ~s   suspend=n
#                         <number>        sets the port
#   any other option      stop parsing launcher options
#
# NOTE: nuts itself also defines a "--debug" option, meaning "run the app
# that nuts launches in debug mode" - different from debugging the
# launcher's own JVM. Plain "--debug"/"--debug=..." are deliberately NOT
# matched below, so they pass straight through to nuts, untouched.
#
# Parsing stops at the first token that isn't "--J="/"--jdb"/"--"; everything
# from that point on, including anything after an explicit "--", is left
# untouched and passed straight through to nuts. NUTS_EXTRA_JAVA_OPTS and
# NUTS_DEBUG_OPTS are real PowerShell arrays, splatted (@array) into the
# final call - each element reaches java.exe as exactly one argument, even
# if it contains spaces. No re-quoting or word-splitting caveats here,
# unlike the sh/cmd variants.

$NUTS_EXTRA_JAVA_OPTS = @()
if ($env:NUTS_JAVA_OPTIONS) {
    $NUTS_EXTRA_JAVA_OPTS += ($env:NUTS_JAVA_OPTIONS -split '\s+') | Where-Object { $_ -ne '' }
}
$NUTS_DEBUG_OPTS = @()

$rest = @($args)
$i = 0
while ($i -lt $rest.Count) {
    $cur = $rest[$i]
    if ($cur -like '--J=*') {
        $NUTS_EXTRA_JAVA_OPTS += $cur.Substring(4)
        $i++
        continue
    } elseif ($cur -eq '--jdb') {
        $NUTS_DEBUG_OPTS = @('-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005')
        $i++
        continue
    } elseif ($cur -like '--jdb=*') {
        $sub = $cur.Substring(6)
        $dPort = 5005
        $dEnable = $true
        $dSuspend = 'y'
        foreach ($tok in ($sub -split ',')) {
            switch ($tok) {
                ''          { }
                'no'        { $dEnable = $false }
                'suspend'   { $dSuspend = 'y' }
                's'         { $dSuspend = 'y' }
                '~suspend'  { $dSuspend = 'n' }
                '~s'        { $dSuspend = 'n' }
                default {
                    if ($tok -match '^\d+$') {
                        $dPort = $tok
                    } else {
                        [Console]::Error.WriteLine("$tok is unsupported")
                    }
                }
            }
        }
        if ($dEnable) {
            $NUTS_DEBUG_OPTS = @("-agentlib:jdwp=transport=dt_socket,server=y,suspend=$dSuspend,address=$dPort")
        }
        $i++
        continue
    } else {
        break
    }
}

if ($i -lt $rest.Count) {
    $appArgs = $rest[$i..($rest.Count - 1)]
} else {
    $appArgs = @()
}

& $_java @NUTS_DEBUG_OPTS @NUTS_EXTRA_JAVA_OPTS -jar "$$NUTS_APP_JAR$$" @appArgs
exit $LASTEXITCODE
# END-COMMAND