@echo off
REM THIS FILE IS GENERATED BY
REM      $$GENERATOR$$
REM DO NOT EDIT IT MANUALLY
REM
REM START-ID
REM      $$NUTS_ID$$
REM END-ID
REM
REM START-COMMAND

setlocal EnableExtensions
REM Deliberately NOT EnableDelayedExpansion: accumulator variables are built
REM via "call :subroutine" instead of "!var!". This keeps "!" a perfectly
REM ordinary character everywhere (needed for the "!suspend"/"!s" negation
REM tokens below, spelled identically to every other shell target) and
REM avoids a whole class of delayed-expansion parsing pitfalls.

call "$$SCRIPT_NUTS_ENV$$"

REM --- resolve the java executable used to run the nuts launcher itself ---
REM Order: NUTS_JAVA_HOME -> JAVA_HOME -> java on PATH.
REM No download/auto-provisioning here on purpose: a bootstrap JVM is
REM required to even run nuts-app.jar, so there is no Java code yet to
REM delegate to. Version/JDK selection for the app that nuts *launches* is
REM nuts' own job, once it is running.
set "_java="
if defined NUTS_JAVA_HOME if exist "%NUTS_JAVA_HOME%\bin\java.exe" set "_java=%NUTS_JAVA_HOME%\bin\java.exe"
if not defined _java if defined JAVA_HOME if exist "%JAVA_HOME%\bin\java.exe" set "_java=%JAVA_HOME%\bin\java.exe"
if not defined _java for /f "delims=" %%J in ('where java 2^>nul') do if not defined _java set "_java=%%J"
if not defined _java (
    echo no java found ^(checked NUTS_JAVA_HOME, JAVA_HOME, PATH^); please install a JDK 8+ or set NUTS_JAVA_HOME/JAVA_HOME 1>&2
    exit /b 203
)

REM "openjdk version "21.0.10" ..." / "java version "1.8.0_202"" -> token 3
REM --- resolve java version safely ---
set "_jver="
for /f "tokens=3" %%V in ('"%_java%" -version 2^>^&1 ^| findstr /i "version"') do (
    if not defined _jver set "_jver=%%~V"
)

REM "openjdk version "21.0.10" ..." / "java version "1.8.0_202"" -> token 3
set "_jver="
for /f "tokens=3" %%V in ('@ "%_java%" -version 2^>^&1 ^| findstr /i "version"') do if not defined _jver set "_jver=%%~V"

REM "1.8.0_202" -> 8 ; "17.0.2" -> 17 ; "11-ea" -> 11 ; "21" -> 21
set "_major="
if defined _jver (
    echo %_jver%| findstr /r "^1\." >nul
    if not errorlevel 1 (
        for /f "tokens=1,2 delims=." %%a in ("%_jver%") do set "_major=%%b"
    ) else (
        for /f "tokens=1 delims=.-" %%a in ("%_jver%") do set "_major=%%a"
    )
)

set "_isnum=1"
if not defined _major set "_isnum=0"
if defined _major for /f "delims=0123456789" %%c in ("%_major%") do set "_isnum=0"

if "%_isnum%"=="0" (
    echo warning: unable to determine java version from '%_jver%', skipping version check 1>&2
    set "_major="
) else (
    call :check_java_version
)

REM --- parse launcher-only options from the leading arguments ---
REM These configure how THIS launcher (nuts) itself is started (the
REM bootstrap JVM). They are consumed here and NOT forwarded to nuts.
REM
REM All of them live under "--" (double-dash), since single-dash is nuts'
REM own combinable short-option space and must not be shadowed here.
REM
REM   --J=<jvmopt>       forward <jvmopt> verbatim as an extra JVM option to
REM                         the launcher (repeatable), e.g. --J=-Xmx512m
REM   --jdb               attach a debugger to the launcher's own JVM on
REM                         port 5005, suspended
REM   --jdb=[port][,opt[,opt...]]  configure the launcher debug agent:
REM                         no             disable debug
REM                         suspend | s     suspend=y
REM                         !suspend | !s   suspend=n
REM                         <number>        sets the port
REM   --                   stop parsing launcher options
REM
REM NOTE: nuts itself also defines a "--debug" option, meaning "run the app
REM that nuts launches in debug mode" - different from debugging the
REM launcher's own JVM. Plain "--debug"/"--debug=..." are deliberately NOT
REM matched below, so they pass straight through to nuts, untouched.
REM
REM Parsing stops at the first token that isn't "--J="/"--jdb"/"--";
REM everything from that point on, including anything after an explicit
REM "--", is left untouched and passed straight through to nuts. Batch has
REM no arrays and "shift" does not update "%*", so remaining args are
REM rebuilt token-by-token via :append_rest, re-quoted per token - this
REM preserves values containing spaces, but (unlike the POSIX/array
REM variants) cannot perfectly round-trip a value containing an embedded
REM double quote or a poison character (& | < > ^) - an inherent cmd.exe
REM limitation, not specific to this script.

set "NUTS_EXTRA_JAVA_OPTS=%NUTS_JAVA_OPTIONS%"
set "NUTS_DEBUG_ARG="
set "REST="

:parse_args
if "%~1"=="" goto do_exec
if "%~1"=="--" (
    shift
    goto collect_rest
)
set "_first4=%~1"
set "_first4=%_first4:~0,4%"
if "%_first4%"=="--J=" (
    call :append_opt "%~1"
    shift
    goto parse_args
)
if "%~1"=="--jdb" (
    set "NUTS_DEBUG_ARG=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
    shift
    goto parse_args
)
set "_first6=%~1"
set "_first6=%_first6:~0,6%"
if "%_first6%"=="--jdb=" (
    call :parse_jdb "%~1"
    shift
    goto parse_args
)
goto collect_rest

:collect_rest
if "%~1"=="" goto do_exec
call :append_rest "%~1"
shift
goto collect_rest

:do_exec
"%_java%" %NUTS_DEBUG_ARG% %NUTS_EXTRA_JAVA_OPTS% -jar "$$NUTS_APP_JAR$$" %REST%
exit /b %errorlevel%

REM --- subroutines (avoid delayed expansion; each call gets a fresh,
REM     correctly-ordered %var% substitution) ---

:append_opt
set "_v=%~1"
set "_v=%_v:--J==%"
set "NUTS_EXTRA_JAVA_OPTS=%NUTS_EXTRA_JAVA_OPTS% "%_v%""
goto :eof

:append_rest
set "REST=%REST% "%~1""
goto :eof

:parse_jdb
set "_v=%~1"
set "_v=%_v:--jdb==%"
set "_sub=%_v%,"
set "_d_port=5005"
set "_d_enable=true"
set "_d_suspend=y"
for %%p in (%_sub:,= %) do call :jdb_token "%%p"
if "%_d_enable%"=="true" set "NUTS_DEBUG_ARG=-agentlib:jdwp=transport=dt_socket,server=y,suspend=%_d_suspend%,address=%_d_port%"
goto :eof

:jdb_token
set "_tok=%~1"
if "%_tok%"=="" goto :eof
if "%_tok%"=="no" (
    set "_d_enable=false"
    goto :eof
)
if "%_tok%"=="suspend" (
    set "_d_suspend=y"
    goto :eof
)
if "%_tok%"=="s" (
    set "_d_suspend=y"
    goto :eof
)
if "%_tok%"=="!suspend" (
    set "_d_suspend=n"
    goto :eof
)
if "%_tok%"=="!s" (
    set "_d_suspend=n"
    goto :eof
)
echo %_tok%| findstr /r "^[0-9][0-9]*$" >nul
if not errorlevel 1 (
    set "_d_port=%_tok%"
) else (
    echo %_tok% is unsupported 1>&2
)
goto :eof

:check_java_version
if %_major% LSS 8 (
    echo expected 1.8+ java version, found %_jver% 1>&2
    exit /b 204
)
goto :eof


REM END-COMMAND