#!/bin/sh
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

. $$SCRIPT_NUTS_ENV$$

# --- resolve the java executable used to run the nuts launcher itself ---
# Order: NUTS_JAVA_HOME -> JAVA_HOME -> java on PATH.
# No download/auto-provisioning here on purpose: a bootstrap JVM is required
# to even run nuts-app.jar, so there is no Java code yet to delegate to.
# Version/JDK selection for the app that nuts *launches* is nuts' own job,
# once it is running (it has a real HTTP client, cache, per-OS logic, etc.).
if [ -n "$NUTS_JAVA_HOME" ] && [ -x "$NUTS_JAVA_HOME/bin/java" ]; then
    _java="$NUTS_JAVA_HOME/bin/java"
elif [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ]; then
    _java="$JAVA_HOME/bin/java"
elif command -v java >/dev/null 2>&1; then
    _java=java
else
    echo "no java found (checked NUTS_JAVA_HOME, JAVA_HOME, PATH); please install a JDK 8+ or set NUTS_JAVA_HOME/JAVA_HOME" >&2
    exit 203
fi

version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
# "1.8.0_202" -> 8 ; "17.0.2" -> 17 ; "11-ea" -> 11 ; "21" -> 21
case "$version" in
    1.*) major=$(echo "$version" | cut -d. -f2) ;;
    *)   major=$(echo "$version" | cut -d. -f1 | cut -d- -f1) ;;
esac
case "$major" in
    ''|*[!0-9]*)
        echo "warning: unable to determine java version from '$version', skipping version check" >&2
        major=""
        ;;
esac
if [ -n "$major" ] && [ "$major" -lt "8" ]; then
    echo "expected 1.8+ java version, found $version" >&2
    exit 204
fi

# --- parse launcher-only options from the leading arguments ---
# These configure how THIS launcher (nuts) itself is started (the bootstrap
# JVM). They are consumed here and NOT forwarded to nuts.
#
# All of them live under "--" (double-dash), since single-dash is nuts' own
# combinable short-option space (-L, -d, ...) and must not be shadowed here.
#
#   --J=<jvmopt>       forward <jvmopt> verbatim as an extra JVM option to
#                         the launcher (repeatable), e.g. --J=-Xmx512m
#                         --J=-Dfoo=bar
#   --jdb               attach a debugger to the launcher's own JVM on port
#                         5005, suspended
#   --jdb=[port][,opt[,opt...]]  configure the launcher debug agent:
#                         no             disable debug
#                         suspend | s     suspend=y
#                         !suspend | !s   suspend=n
#                         <number>        sets the port
#   any other option      stop parsing launcher options
#
# NOTE: nuts itself also defines a "--debug" option, meaning "run the app
# that nuts launches in debug mode" - a different thing from debugging the
# launcher's own JVM. "--debug"/"--debug=..." are deliberately NOT matched
# below, so they pass straight through in "$@" to nuts, untouched.
#
# Parsing stops at the first token that isn't "--J="/"--jdb"/"--"; everything
# from that point on, including anything after an explicit "--", is left
# untouched in "$@" and passed straight through to nuts.
#
# POSIX sh has no arrays: NUTS_EXTRA_JAVA_OPTS/_NUTS_JAVA_OPTIONS are plain
# strings, relying on word-splitting at exec time (same as $@ itself would
# be without quotes). A --J= value containing a literal space will therefore
# be split into two argv entries - this is an inherent POSIX sh limitation,
# not present in the bash/zsh/fish variants, which use real arrays instead.

NUTS_DEBUG_ARG=""
NUTS_EXTRA_JAVA_OPTS=""

while [ $# -gt 0 ]; do
    case "$1" in
        --J=*)
            NUTS_EXTRA_JAVA_OPTS="$NUTS_EXTRA_JAVA_OPTS ${1#--J=}"
            shift
            ;;
        --jdb)
            NUTS_DEBUG_ARG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
            shift
            ;;
        --jdb=*)
            sub="${1#--jdb=},"
            d_port=5005
            d_enable="true"
            d_suspend="y"
            for curr in $(echo "$sub" | tr "," "\n"); do
                case "$curr" in
                    '') : ;;
                    no)         d_enable="false" ;;
                    suspend|s)  d_suspend="y" ;;
                    '!suspend'|'!s') d_suspend="n" ;;
                    *[!0-9]*)   echo "$curr is unsupported" >&2 ;;
                    *)          d_port="$curr" ;;
                esac
            done
            if [ "$d_enable" = 'true' ]; then
                NUTS_DEBUG_ARG="-agentlib:jdwp=transport=dt_socket,server=y,suspend=$d_suspend,address=$d_port"
            fi
            shift
            ;;
        *)
            break
            ;;
    esac
done

_NUTS_JAVA_OPTIONS=$(echo "$NUTS_JAVA_OPTIONS $NUTS_EXTRA_JAVA_OPTS -jar" | xargs)

exec "$_java" $NUTS_DEBUG_ARG $_NUTS_JAVA_OPTIONS "$$NUTS_APP_JAR$$" "$@"
# END-COMMAND