#!/usr/bin/env fish
# THIS FILE IS GENERATED BY
#      $$GENERATOR$$
# DO NOT EDIT IT MANUALLY
#
# START-ID
#      $$NUTS_ID$$
# END-ID
#
# START-COMMAND

source $$SCRIPT_NUTS_ENV$$

# --- resolve the java executable used to run the nuts launcher itself ---
# Order: NUTS_JAVA_HOME -> JAVA_HOME -> java on PATH.
# No download/auto-provisioning here on purpose: a bootstrap JVM is required
# to even run nuts-app.jar, so there is no Java code yet to delegate to.
# Version/JDK selection for the app that nuts *launches* is nuts' own job,
# once it is running (it has a real HTTP client, cache, per-OS logic, etc.).
set -l _java
if test -n "$NUTS_JAVA_HOME"; and test -x "$NUTS_JAVA_HOME/bin/java"
    set _java "$NUTS_JAVA_HOME/bin/java"
else if test -n "$JAVA_HOME"; and test -x "$JAVA_HOME/bin/java"
    set _java "$JAVA_HOME/bin/java"
else if command -v java >/dev/null 2>&1
    set _java java
else
    echo "no java found (checked NUTS_JAVA_HOME, JAVA_HOME, PATH); please install a JDK 8+ or set NUTS_JAVA_HOME/JAVA_HOME" 1>&2
    exit 203
end

set -l _java_version ($_java -version 2>&1 | awk -F '"' '/version/ {print $2}')
# "1.8.0_202" -> 8 ; "17.0.2" -> 17 ; "11-ea" -> 11 ; "21" -> 21
set -l vparts (string split '.' -- $_java_version)
set -l major
if test "$vparts[1]" = "1"
    set major $vparts[2]
else
    set major (string split '-' -- $vparts[1])[1]
end
if not string match -qr '^[0-9]+$' -- $major
    echo "warning: unable to determine java version from '$_java_version', skipping version check" 1>&2
    set major ""
end
if test -n "$major"; and test $major -lt 8
    echo "expected 1.8+ java version, found $_java_version" 1>&2
    exit 204
end

# --- parse launcher-only options from the leading arguments ---
# These configure how THIS launcher (nuts) itself is started (the bootstrap
# JVM). They are consumed here and NOT forwarded to nuts.
#
# All of them live under "--" (double-dash), since single-dash is nuts' own
# combinable short-option space (-L, -d, ...) and must not be shadowed here.
#
#   --J=<jvmopt>       forward <jvmopt> verbatim as an extra JVM option to
#                         the launcher (repeatable), e.g. --J=-Xmx512m
#                         --J=-Dfoo=bar
#   --jdb               attach a debugger to the launcher's own JVM on port
#                         5005, suspended
#   --jdb=[port][,opt[,opt...]]  configure the launcher debug agent:
#                         no             disable debug
#                         suspend | s     suspend=y
#                         !suspend | !s   suspend=n
#                         <number>        sets the port
#   any other option      stop parsing launcher options
#
# NOTE: nuts itself also defines a "--debug" option, meaning "run the app
# that nuts launches in debug mode" - a different thing from debugging the
# launcher's own JVM. "--debug"/"--debug=..." are deliberately NOT matched
# below, so they pass straight through in $argv to nuts, untouched.
#
# Parsing stops at the first token that isn't "--J="/"--jdb"/"--"; everything
# from that point on, including anything after an explicit "--", is left
# untouched and passed straight through to nuts.
#
# NUTS_EXTRA_JAVA_OPTS and NUTS_DEBUG_OPTS are real fish arrays, so option
# values are never re-split at exec time - each element reaches java as
# exactly one argument, and fish never word-splits on its own either way.

set -l NUTS_EXTRA_JAVA_OPTS
if test -n "$NUTS_JAVA_OPTIONS"
    set NUTS_EXTRA_JAVA_OPTS (string split ' ' -- $NUTS_JAVA_OPTIONS)
end
set -l NUTS_DEBUG_OPTS

while count $argv >/dev/null
    switch $argv[1]
        case '--J=*'
            set NUTS_EXTRA_JAVA_OPTS $NUTS_EXTRA_JAVA_OPTS (string replace -- '--J=' '' $argv[1])
            set argv $argv[2..-1]
        case '--jdb'
            set NUTS_DEBUG_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
            set argv $argv[2..-1]
        case '--jdb=*'
            set -l sub (string replace -- '--jdb=' '' $argv[1]),
            set -l d_port 5005
            set -l d_enable true
            set -l d_suspend y
            for curr in (string split ',' -- $sub)
                switch $curr
                    case ''
                        # ignore empty token
                    case 'no'
                        set d_enable false
                    case 'suspend' 's'
                        set d_suspend y
                    case '!suspend' '!s'
                        set d_suspend n
                    case '*'
                        if string match -qr '^[0-9]+$' -- $curr
                            set d_port $curr
                        else
                            echo "$curr is unsupported" 1>&2
                        end
                end
            end
            if test "$d_enable" = true
                set NUTS_DEBUG_OPTS "-agentlib:jdwp=transport=dt_socket,server=y,suspend=$d_suspend,address=$d_port"
            end
            set argv $argv[2..-1]
        case '*'
            break
    end
end

exec $_java $NUTS_DEBUG_OPTS $NUTS_EXTRA_JAVA_OPTS -jar "$$NUTS_APP_JAR$$" $argv
# END-COMMAND