package net.thevpc.nuts.concurrent;

import net.thevpc.nuts.text.NMsg;

import java.util.function.Consumer;
import java.util.function.Function;

/**
 * Represents the result of an attempt to acquire or consume permits
 * from a {@link NRateLimitValue}.
 * <p>
 * This interface provides methods to check whether the attempt succeeded,
 * handle success and failure cases, and optionally execute callbacks
 * or throw exceptions when the attempt fails.
 *
 * @since 0.8.7
 */
public interface NRateLimitValueResult {

    /**
     * Checks whether the attempt to acquire permits was successful.
     *
     * @return true if the requested permits were acquired, false otherwise
     */
    boolean success();

    /**
     * Throws a runtime exception if the attempt was not successful.
     *
     * @return this result if successful
     * @throws RuntimeException if the attempt failed
     */
    NRateLimitValueResult orElseError();

    /**
     * Throws a runtime exception generated by the given function if the attempt failed.
     *
     * @param other function that produces a {@link RuntimeException} from a failure message
     * @return this result if successful
     * @throws RuntimeException if the attempt failed
     */
    NRateLimitValueResult orElseThrow(Function<NMsg, RuntimeException> other);

    /**
     * Executes the given {@link Runnable} if the attempt succeeded.
     *
     * @param r the action to execute on success
     * @return this result
     */
    NRateLimitValueResult onSuccess(Runnable r);

    /**
     * Executes the given {@link NCallable} if the attempt succeeded.
     *
     * @param r the callable to execute on success
     * @param <T> the type of the result from the callable
     * @return this result
     */
    <T> NRateLimitValueResult onSuccessCall(NCallable<T> r);

    /**
     * Executes the given {@link Consumer} with a failure message
     * if the attempt was not successful.
     *
     * @param r the action to execute on failure
     * @return this result
     */
    NRateLimitValueResult orElse(Consumer<NMsg> r);

    /**
     * Executes the given function with a failure message and returns
     * its result if the attempt was not successful.
     *
     * @param r function that produces a result from a failure message
     * @param <T> the type of the result
     * @return the result from the function if failed, otherwise the acquired value
     */
    <T> NRateLimitValueResult orElseCall(Function<NMsg, T> r);

    /**
     * Returns the value associated with this result.
     * <p>
     * This may throw an exception if the attempt failed and no
     * fallback was provided.
     *
     * @param <T> the type of the value
     * @return the acquired value
     * @throws RuntimeException if the attempt was not successful
     */
    <T> T get();
}
