package net.thevpc.nuts.runtime.standalone.workspace;

import net.thevpc.nuts.app.NApplicationHandleMode;
import net.thevpc.nuts.app.NApplicationMode;
import net.thevpc.nuts.artifact.*;
import net.thevpc.nuts.cmdline.NArgType;
import net.thevpc.nuts.cmdline.NCmdLineFormatStrategy;
import net.thevpc.nuts.command.*;
import net.thevpc.nuts.concurrent.*;
import net.thevpc.nuts.core.*;
import net.thevpc.nuts.elem.*;
import net.thevpc.nuts.expr.NExprCommonOp;
import net.thevpc.nuts.expr.NExprNodeType;
import net.thevpc.nuts.expr.NExprOpType;
import net.thevpc.nuts.io.*;
import net.thevpc.nuts.math.NIndexSelectionStrategy;
import net.thevpc.nuts.net.NHttpMethod;
import net.thevpc.nuts.platform.*;
import net.thevpc.nuts.reflect.NReflectPropertyAccessStrategy;
import net.thevpc.nuts.reflect.NReflectPropertyDefaultValueStrategy;
import net.thevpc.nuts.runtime.standalone.app.cmdline.DefaultNCmdLines;
import net.thevpc.nuts.runtime.standalone.format.DefaultNObjectObjectWriter;
import net.thevpc.nuts.runtime.standalone.format.NDisplayProperty;
import net.thevpc.nuts.runtime.standalone.format.tson.parser.NElementTokenType;
import net.thevpc.nuts.runtime.standalone.io.terminal.NTerminalModeOp;
import net.thevpc.nuts.runtime.standalone.repository.cmd.NRepositorySupportedAction;
import net.thevpc.nuts.runtime.standalone.repository.impl.main.NInstallLogAction;
import net.thevpc.nuts.runtime.standalone.workspace.cmd.search.SearchExecType;
import net.thevpc.nuts.runtime.standalone.workspace.config.ConfigEventType;
import net.thevpc.nuts.spi.NScopeType;
import net.thevpc.nuts.spi.NSelectorOp;
import net.thevpc.nuts.text.*;
import net.thevpc.nuts.time.NDurationFormatMode;
import net.thevpc.nuts.time.NProgressEventType;
import net.thevpc.nuts.util.*;

public class NativeImageHelper {
    public static void prepare(){
        if(Boolean.getBoolean("EnableGraalVM")){
            new DefaultNCmdLines();
            new DefaultNObjectObjectWriter();
            //load enums
            NStoreType.parse("");
            NOsFamily.parse("");
            NDesktopEnvironmentFamily.parse("");
            NElementTypeGroup.parse("");
            NTerminalModeOp.parse("");
            NIndexSelectionStrategy.parse("");
            NNewLineMode.parse("");
            NNameSelectorStrategy.parse("");
            NTextFormatType.parse("");
            NExecutionEngineFamily.parse("");
            NPathStandardOption.parse("");
            NAffixType.parse("");
            NDependencyScopePattern.parse("");
            NRateLimitDefaultStrategy.parse("");
            NExprCommonOp.parse("");
            NWordFormat.parse("");
            NPathType.parse("");
            NStoreScope.parse("");
            NMapSideStrategy.parse("");
            NMemoryUnit.parse("");
            NProgressEventType.parse("");
            NExprOpType.parse("");
            NVisitResult.parse("");
            NFilterOp.parse("");
            NNumberLayout.parse("");
            NCmdLineFormatStrategy.parse("");
            NpsStatus.parse("");
            NIsolationLevel.parse("");
            NExprElementReshaperType.parse("");
            NTextStyleType.parse("");
            NShellFamily.parse("");
            NHttpMethod.parse("");
            NDiffMode.parse("");
            NReflectPropertyAccessStrategy.parse("");
            NPathPermission.parse("");
            NDescriptorStyle.parse("");
            NHomeLocation.parse("");
            NDependencyScope.parse("");
            NSelectorOp.parse("");
            NPathExtensionType.parse("");
            SearchExecType.parse("");
            NExprNodeType.parse("");
            NDecisionConflict.parse("");
            NApplicationMode.parse("");
            NOsServiceType.parse("");
            NStoreType.parse("");
            NElementType.parse("");
            NDecision.parse("");
            NpsType.parse("");
            NOperatorPosition.parse("");
            NContentType.parse("");
            NTextType.parse("");
            NOperatorSymbol.parse("");
            NDescriptorFlag.parse("");
            NStoreStrategy.parse("");
            NAffixAnchor.parse("");
            NSupportMode.parse("");
            NScopeType.parse("");
            NIteratorErrorHandlerType.parse("");
            NSpeedQualifier.parse("");
            NFetchMode.parse("");
            NSagaStatus.parse("");
            NDesktopIntegrationItem.parse("");
            NSagaNodeType.parse("");
            NSagaNodeStatus.parse("");
            NWorkBalancerDefaultStrategy.parse("");
            NRunAsMode.parse("");
            NPositionType.parse("");
            NElementFormatterStyle.parse("");
            NExecutionType.parse("");
            NOptionalType.parse("");
            NDisplayProperty.parse("");
            NTextStyle.parse("");
            NDurationFormatMode.parse("");
            NSysEditorFamily.parse("");
            NRedirectType.parse("");
            NTableSeparator.parse("");
            NTerminalMode.parse("");
            NExecutableType.parse("");
            NInstallLogAction.parse("");
            NOperatorAssociativity.parse("");
            NOpenEnum.parse(NOpenEnum.class,"");
            NApplicationHandleMode.parse("");
            NTreeVisitResult.parse("");
            NColorBits.parse("");
            NIdType.parse("");
            NFetchStrategy.parse("");
            ConfigEventType.parse("");
            NReflectPropertyDefaultValueStrategy.parse("");
            NCompensationStrategy.parse("");
            NTextStyles.parse("");
            NMatchType.parse("");
            NArchFamily.parse("");
            NConfirmationMode.parse("");
            NOpenMode.parse("");
            NElementTokenType.parse("");
            NRepositorySupportedAction.parse("");
            NArgType.parse("");

        }
    }
}
